name:                GlobPatternMatcher
version:             0.1.0.0
github:              "Antigen-1/GlobPatternMatcher"
license:             BSD-3-Clause
author:              "ZhangHao"
maintainer:          "zhanghao@antigen.top"
copyright:           "2023 ZhangHao"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Unix-like glob pattern matcher

dependencies:
- base >= 4.7 && < 5
- regex == 1.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  GlobPatternMatcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GlobPatternMatcher

tests:
  GlobPatternMatcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GlobPatternMatcher
